// Code generated by genindex.go. DO NOT EDIT.
package solutions
var SolutionIndex = map[string]interface{}{
  "P10": P10,
  "P12": P12,
  "P13": P13,
  "P5": P5,
  "P8": P8,
  "P11": P11,
  "P4": P4,
  "P9": P9,
  "P14": P14,
  "P2": P2,
  "P3": P3,
  "P6": P6,
  "P1": P1,
  "P7": P7,
}
