// Code generated by genindex.go. DO NOT EDIT.
package solutions

var SolutionIndex = map[string]func() int{
	"P4":  P4,
	"P5":  P5,
	"P7":  P7,
	"P10": P10,
	"P3":  P3,
	"P8":  P8,
	"P9":  P9,
	"P1":  P1,
	"P2":  P2,
	"P6":  P6,
}
