(defn repl
  (nsp)
  (def tmp (fprintf stdout "> "))
  (switch (read stdin)
	  ((:eof)
	   (fprintf stdout "\n"))
	  ((:ok datum)
	   (switch (eval-in nsp datum)
		   ((:ok val)
		    (ignore (print val))
		    (repl nsp))
		   ((:err msg)
		    (ignore (fprintf-bytestring stderr "eval error: %s\n" msg))
		    (repl nsp))
		   ((:context ctxt)
		    (repl ctxt))))
	  ((:err msg)
	   (ignore (fprintf-bytestring stderr "read error: %s\n" msg))
	   (repl nsp))))

(ignore (repl namespace-with-builtins))
