(defn repl
  (nsp)
  (fprintf stdout "> ")
  (switch (read stdin)
	  ((:eof)
	   (fprintf stdout "\n"))
	  ((:ok datum)
	   (switch (eval-in nsp datum)
		   ((:ok val)
		    (print val))
		   ((:err msg)
		    (fprintf-bytestring stderr "eval error: %s\n" msg)))
	   (repl nsp))
	  ((:err msg)
	   (fprintf-bytestring stderr "read error: %s\n" msg)
	   (repl nsp))))

(def ns (make-namespace))
(repl ns)
