#!/usr/bin/env python
import sys
import dataclasses
import sexpdata


@dataclasses.dataclass
class State:
    varz: list = dataclasses.field(default_factory=list)
    stak: list = dataclasses.field(default_factory=list)
    ip: int = 0


def is_true(tagged_value):
    tag, val = tagged_value
    if tag != sexpdata.Symbol(":value"):
        return True
    return bool(val)


def check_is_value(tagged_value):
    tag, val = tagged_value
    if tag != sexpdata.Symbol(":value"):
        raise RuntimeError(f"check_is_value {tagged_value}")
    return val

def check_is_routine_0(tagged_value):
    if len(tagged_value) == 3:
        tag, offset, val = tagged_value
        if tag != sexpdata.Symbol(":routine-0"):
            raise RuntimeError(f"check_is_value {tagged_value}")
        (varz, stack) = val
        return offset, (varz, stack)
    if len(tagged_value) == 2:
        offset, varz_and_stack = check_is_value(tagged_value)
        offset = check_is_value(offset)
        varz, stack = check_is_value(varz_and_stack)
        varz = check_is_value(varz)
        stack = check_is_value(stack)
        return offset, (varz, stack)


def check_is_cons(tagged_value):
    tag, val = tagged_value
    if tag != sexpdata.Symbol(":value"):
        raise RuntimeError(f"check_is_cons {tagged_value}")
    return val[0], [sexpdata.Symbol(":value"), val[1:]]


def make_list_with_items(*args):
    return [sexpdata.Symbol(":value"), list(args)]


def make_routine_0(ip, varz, stak):
    return [sexpdata.Symbol(":routine-0"), ip, [varz, stak]]


def make_symbol(s):
    return [sexpdata.Symbol(":value"), sexpdata.Symbol(s)]


def get_var(d, k):
    for k_, v in reversed(d):
        if k_ == k:
            return v
    raise KeyError(k)


def head(args):
    a1, ar = check_is_cons(args)
    h, t = check_is_cons(a1)
    return h


def tail(args):
    a1, ar = check_is_cons(args)
    h, t = check_is_cons(a1)
    return t


def is_constant(args):
    a1, ar = check_is_cons(args)
    v = check_is_value(a1)
    if isinstance(v, list):
        return make_list_with_items()
    if isinstance(v, sexpdata.Symbol) and str(v)[0] != ":":
        return make_list_with_items()
    return make_list_with_items(make_list_with_items())


def eq(args):
    a1, ar = check_is_cons(args)
    a2, arr = check_is_cons(ar)
    if a1 == a2:
        return make_list_with_items(make_list_with_items())
    return make_list_with_items()


def panic(args):
    a1, ar = check_is_cons(args)
    raise RuntimeError("Panic! {}".format(repr(a1)))


def annotate(args):
    a1, ar = check_is_cons(args)
    tag, val = a1
    if tag == sexpdata.Symbol(":routine-0"):
        r = ":operator"
    elif tag == sexpdata.Symbol(":value"):
        if isinstance(val, list):
            r = ":list"
        elif isinstance(val, sexpdata.Symbol):
            r = ":symbol"
        elif isinstance(val, str):
            r = ":bytestring"
        elif isinstance(val, int):
            r = ":integer"
        else:
            raise RuntimeError("cannot annotate {}".format(repr(a1)))
    else:
        raise RuntimeError("cannot annotate {}".format(repr(a1)))
    return make_list_with_items(make_symbol(r), a1)


def add(args):
    a1, ar = check_is_cons(args)
    a2, arr = check_is_cons(ar)
    x = check_is_value(a1)
    y = check_is_value(a2)
    return [sexpdata.Symbol(":value"), x + y]


def cons(args):
    a1, ar = check_is_cons(args)
    a2, arr = check_is_cons(ar)
    if a1 == a2:
        return make_list_with_items(make_list_with_items())
    a2items = check_is_value(a2)
    return make_list_with_items(a1, *a2items)


def concat_bytestrings(args):
    a1, ar = check_is_cons(args)
    a2, arr = check_is_cons(ar)
    x = check_is_value(a1)
    y = check_is_value(a2)
    return [sexpdata.Symbol(":value"), x + y]


def repre(args):
    a1, ar = check_is_cons(args)
    return [sexpdata.Symbol(":value"), repr(a1)]


def main():
    bc = sys.stdin.read()
    prog = sexpdata.loads(bc)
    ip = 0
    pdata = [[State()]]
    def pop_stack():
        return pdata[-1][-1].stak.pop()
    while True:
        ip = pdata[-1][-1].ip
        ins = prog[ip]
        # print(ins)
        op, args = ins[0], ins[1:]
        if op == sexpdata.Symbol(":end"):
            if len(pdata) != 1 or len(pdata[0]) != 1:
                raise RuntimeError("program ended, but the call stack is not empty")
            break
        elif op == sexpdata.Symbol(":if"):
            if_true, if_false = args
            if is_true(pop_stack()):
                ip = if_true
            else:
                ip = if_false
        elif op == sexpdata.Symbol(":nop"):
            nex, = args
            ip = nex
        elif op == sexpdata.Symbol(":put-const"):
            value, nex = args
            pdata[-1][-1].stak.append(value)
            ip = nex
        elif op == sexpdata.Symbol(":put-var"):
            value, nex = args
            pdata[-1][-1].stak.append(get_var(pdata[-1][-1].varz, value))
            ip = nex
        elif op == sexpdata.Symbol(":args"):
            nex, = args
            pdata[-1][-1].stak.append("__function_call")
            ip = nex
        elif op == sexpdata.Symbol(":call"):
            hat, nex = args
            if hat:
                raise RuntimeError("routine-1 call is not supported yet")
            fnandargs = pop_stack()
            rout, args = check_is_cons(fnandargs)
            offset, (varz, stack) = check_is_routine_0(rout)
            rtvarz = list(varz)
            rtstack = list(stack)
            rtstack.append(args)
            pdata[-1][-1].ip = nex
            pdata[-1].append(State(varz=rtvarz, stak=rtstack, ip=0))  # ip set after endif
            ip = offset
        elif op == sexpdata.Symbol(":host"):
            instruction, nex = args
            arg = pop_stack()
            if isinstance(instruction, list) and len(instruction) == 2 and instruction[0] == "eval":
                res = eval(instruction[1], globals(), {"x": arg})
                pdata[-1][-1].stak.append(res)
            else:
                raise RuntimeError(f"host not implemented: {instruction}")
            ip = nex
        elif op == sexpdata.Symbol(":collect"):
            nex, = args
            form = []
            while True:
                val = pop_stack()
                if val == "__function_call":
                    break
                form = [val] + form
            pdata[-1][-1].stak.append([sexpdata.Symbol(":value"), form])
            ip = nex
        elif op == sexpdata.Symbol(":pop"):
            var, nex = args
            varname = check_is_value(var)
            if varname == sexpdata.Symbol(":void"):
                pop_stack()
            else:
                pdata[-1][-1].varz.append((var, pop_stack()))
            ip = nex
        elif op == sexpdata.Symbol(":set-closures"):
            pr, name, hat, nex = args
            if hat:
                raise RuntimeError("routine-1 set-closures is not supported yet")
            pvarz = list(pdata[-1][-1].varz)
            p = [sexpdata.Symbol(":routine-0"), pr, [pvarz, []]]
            pvarz.append((name, p))
            pdata[-1][-1].varz.append((name, p))
            ip = nex
        elif op == sexpdata.Symbol(":return"):
            hat, = args
            if hat:
                raise RuntimeError("routine-1 return is not supported yet")
            rvalue = pop_stack()
            pdata[-1].pop()
            pdata[-1][-1].stak.append(rvalue)
            ip = pdata[-1][-1].ip
        elif op == sexpdata.Symbol(":yield"):
            hat, nex = args
            rvalue = pop_stack()

            contvarz = list(pdata[-1][-1].varz)
            contstack = list(pdata[-1][-1].stak)
            cont = make_routine_0(varz=contvarz, stak=contstack, ip=nex)

            pdata[-1].pop()
            pdata[-1][-1].stak.append(make_list_with_items(rvalue, cont))
            ip = pdata[-1][-1].ip
        elif op == sexpdata.Symbol(":import"):
            nex, = args
            val = pop_stack()
            val = check_is_value(val)
            _, rout = val
            _, (varz, _) = check_is_routine_0(rout)
            pdata[-1][-1].varz.extend(varz)
            ip = nex
        else:
            raise RuntimeError(op)
        pdata[-1][-1].ip = ip



if __name__ == "__main__":
    main()


"""
  case PROG_END: {return datum_make_list_1(datum_make_symbol(":end")); } break;
  case PROG_IF: {return datum_make_list_3(datum_make_symbol(":if"), prog_to_offset(sl, p->if_true), prog_to_offset(sl, p->if_false));} break;
  case PROG_NOP: {return datum_make_list_2(datum_make_symbol(":nop"), prog_to_offset(sl, p->nop_next));} break;
  case PROG_PUT_CONST: {return datum_make_list_3(datum_make_symbol(":put-const"), datum_to_asm(sl, p->put_const_value), prog_to_offset(sl, p->put_const_next));} break;
  case PROG_PUT_VAR: {return datum_make_list_3(datum_make_symbol(":put-var"), datum_to_asm(sl, p->put_var_value), prog_to_offset(sl, p->put_var_next));} break;
  case PROG_ARGS: {return datum_make_list_2(datum_make_symbol(":args"), prog_to_offset(sl, p->args_next));} break;
  case PROG_CALL: {return datum_make_list_3(datum_make_symbol(":call"), datum_make_int(p->call_hat), prog_to_offset(sl, p->call_next));} break;
  case PROG_HOST: {return datum_make_list_3(datum_make_symbol(":host"), p->host_instruction, prog_to_offset(sl, p->host_next));} break;
  case PROG_COLLECT: {return datum_make_list_2(datum_make_symbol(":collect"), prog_to_offset(sl, p->collect_next));} break;
  case PROG_POP: {return datum_make_list_3(datum_make_symbol(":pop"), datum_to_asm(sl, p->pop_var), prog_to_offset(sl, p->pop_next));} break;
  case PROG_SET_CLOSURES: {return datum_make_list_5(datum_make_symbol(":set-closures"), prog_to_offset(sl, p->set_closures_prog), datum_to_asm(sl, p->set_closures_name), datum_make_int(p->set_closures_hat), prog_to_offset(sl, p->set_closures_next));} break;
  case PROG_RETURN: {return datum_make_list_2(datum_make_symbol(":return"), datum_make_int(p->return_hat));} break;
  case PROG_YIELD: {return datum_make_list_3(datum_make_symbol(":yield"), datum_make_int(p->yield_hat), prog_to_offset(sl, p->yield_next));} break;
  case PROG_IMPORT: {return datum_make_list_2(datum_make_symbol(":import"), prog_to_offset(sl, p->import_next));} break;
"""
