#!/bin/sh
cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug \
      && cmake --build build --target codegen \
      && cmake --build build \
      && cmake --build build --target test ARGS=-V
