#!/bin/sh
mkdir -p darwin
mkdir -p linux

go build -o darwin/crsh-server cmd/server/main.go || exit
go build -o darwin/crsh-client cmd/client/main.go || exit
go build -o darwin/crsh2 cmd/crsh2/main.go || exit
GOOS=linux GOARCH=amd64 go build -o linux/crsh-server cmd/server/main.go || exit
GOOS=linux GOARCH=amd64 go build -o linux/crsh-client cmd/client/main.go || exit

(
	cd darwin
	for file in *; do
		rm -f ~/.local/bin/$file || exit
		cp $file ~/.local/bin || exit
	done
)
(
	cd universal
	for file in *; do
		rm -f ~/.local/bin/$file || exit
		cp $file ~/.local/bin || exit
	done
)
rm -rf ~/.local/share/crsh
mkdir -p ~/.local/share/crsh
cp -r darwin linux universal ~/.local/share/crsh

exec ~/.local/bin/crsh2
