#!/usr/bin/env bash

echo "Starting ssh wrapper" | nc -U /tmp/crsh.log

chan="$1"
name="$2"

ssh -L "$chan:$chan" -R "/tmp/crsh.log:/tmp/crsh.log" ma "crsh-server-in-abduco $chan $name; rm /tmp/crsh.log" 2> >( nc -U /tmp/crsh.log )

echo "Exiting ssh wrapper" | nc -U /tmp/crsh.log
