#!/bin/bash
rm -rf /tmp/crsh-command
mkfifo /tmp/crsh-command

rm -rf /tmp/crsh-result
mkfifo /tmp/crsh-result

echo "server will enter the loop" >>/tmp/crsh-log

{
	tput cup $(tput lines) 0 </dev/tty >/dev/tty 
	echo "server did enter the loop" >>/tmp/crsh-log
	while true;
	do
		IFS= read -r cmd
	  echo "server did read a command $cmd" >>/tmp/crsh-log
		if [ -z "$cmd" ]; then
			break
		fi
		echo "> $cmd" </dev/tty >/dev/tty
    # Also wait a bit.
		sleep 1
	  echo "server will eval $cmd" >>/tmp/crsh-log
		# vim </dev/tty >/dev/tty
		eval "$cmd" </dev/tty >/dev/tty
		status="$?"
	  echo 'server did eval' >>/tmp/crsh-log
		echo "$status"
	  echo 'server did send status' >>/tmp/crsh-log
	done
} </tmp/crsh-command >/tmp/crsh-result
