#!/usr/bin/env bash

kitty @ goto-layout splits
kitty @ launch --self --location hsplit --cwd current crsh prompt tcp://localhost:5678
kitty @ resize-window --self --axis vertical --increment +1000
crsh-server manager -name default2 tcp://localhost:5678
