#!/bin/bash
chan=$1
server=$2

echo '' >>/tmp/crsh-log
echo 'STARTING NEW SESSION' >>/tmp/crsh-log
echo '' >>/tmp/crsh-log

echo "client will enter the loop" >>/tmp/crsh-log
while true; do
  echo "client will read a result" >>/tmp/crsh-log
  IFS= read -r res
  echo "client did read the result $res" >>/tmp/crsh-log
  if [ -z "$res" ]; then
    break
  fi
  echo "client will read a line" >>/tmp/crsh-log
  kitty @ focus-window
  lines=$(tput lines </dev/tty)
  tput cup $(($lines - 1)) 0 </dev/tty >/dev/tty
  printf "\x1b[38;5;251m@${server}\x1b[K\x1b[0m" </dev/tty >/dev/tty
  tput cup 0 0 </dev/tty >/dev/tty
  ./third-party/linenoise-master/linenoise_main /tmp/linenoise-result </dev/tty >/dev/tty
  line=$(cat /tmp/linenoise-result)
  echo "client did read a line $line" >>/tmp/crsh-log
  clear >/dev/tty </dev/tty
  kitty @ focus-window -m "cmdline:.*crsh-.*"
  echo "$line"
  echo "client did send the line" >>/tmp/crsh-log
  if [ "$line" = "exit" ]; then
    break
  fi
done >$chan/command <$chan/result 
