#!/bin/bash

ssh ma 'rm -rf /tmp/crsh-command && mkfifo /tmp/crsh-command'
echo 'init socket'
{
	cat /tmp/crsh-command | ssh ma 'cat >/tmp/crsh-command'
}&
echo 'forward local crsh-command'
ssh ma crsh-server
