#!/usr/bin/env bash

echo "Starting ssh wrapper" | nc localhost 5678

chan="$1"
name="$2"

ssh -L "$chan:$chan" -R "5678:localhost:5678" ma "crsh-server-in-abduco $chan $name" 2> >( nc localhost 5678 )

echo "Exiting ssh wrapper" | nc localhost 5678
