#!/bin/bash
set -m

function get_pid() {
  exec sh -c 'echo "$PPID"'
}

( while true; do read -p a: -r line; kill -STOP $(get_pid); done )
( while true; do read -p b: -r line; kill -STOP $(get_pid); done ) 

while true; do
  fg %- >/dev/null
done
