name:                filesearch
version:             0.1.0.0

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- filepath == 1.4.2.1
- directory == 1.3.4.0
- time == 1.9.3

library:
  source-dirs: src

executables:
  filesearch:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filesearch

tests:
  filesearch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filesearch
