#!/bin/sh
name="$1"
chan="/tmp/crsh-${name}.sock"

kitty @ goto-layout tall

winid=$( \
	kitty @ launch \
		--title "crsh-server-${name}" \
		--location=before \
		bash -c "kitty @ resize-window --self -a vertical -i +1000 2> >( ~/.local/bin/crsh-logclient );
             ~/.local/bin/crsh-server-in-ssh $chan $name")

~/.local/bin/crsh-client \
  --clear \
	--on-prompt 'kitty @ focus-window' \
  --on-exec 'kitty @ focus-window -m title:.*crsh-server.*' "$chan"

kitty @ send-text --match "title:crsh-server-${name}" '\c\'

