#!/bin/sh
name="$1"
chan="/tmp/crsh-${name}.sock"

winid=$(kitty @ launch --title "crsh-server-${name}" --location=before bash -c "kitty @ resize-window --self -a vertical -i +1000 2>/dev/null; ~/.local/bin/crsh-server-in-ssh $chan $name")

~/.local/bin/crsh-client "$chan" "$@"
kitty @ send-text --match "title:crsh-server-${name}" '\c\'

