#!/usr/bin/env bash

echo "Starting abduco wrapper" | ~/.local/bin/crsh-logclient

chan="$1"
name="$2"

~/.local/bin/abduco -A "$name" ~/.local/bin/crsh-server "$chan" 2> >( ~/.local/bin/crsh-logclient )
echo "Abduco wrapper: server exit status $?" | ~/.local/bin/crsh-logclient

echo "Exiting abduco wrapper" | ~/.local/bin/crsh-logclient
