#!/usr/bin/env sh

if [[ "$(uname)" == "Linux" ]]; then
	showinfo() {
		ldd $1
	}
	SUFFIX=so
elif [[ "$(uname)" == "Darwin" ]]; then
	showinfo() {
		otool -L $1
		otool -l $1 | grep RC_RPATH
	}
	withdebug() {
		DYLD_PRINT_SEARCHING=1 "$@"
	}
	SUFFIX=dylib
fi

rm -rf dev

mkdir -p dev
mkdir -p dev/subdir
mkdir -p dev/bindir
mkdir -p dev/tmp

clang++ -o dev/libmylib.$SUFFIX -shared mylib.cpp
ln -s ../libmylib.$SUFFIX dev/subdir/libmylib-symlink.$SUFFIX

docheck() {
	echo "========= $1 ============="
	showinfo $1
	withdebug $1
	(
		cd dev/tmp
		withdebug ../../$1
	)
}

clang++ -o dev/hello1 -L./dev -lmylib hello.cpp && docheck dev/hello1
clang++ -o dev/bindir/hello2 -L./dev -lmylib hello.cpp && docheck dev/bindir/hello2
clang++ -o dev/hello3 -L./dev/subdir -lmylib-symlink hello.cpp && docheck dev/hello3

