#!/usr/bin/env sh

export CXX=${CXX:-c++}

if [[ "$(uname)" == "Linux" ]]; then
	showinfo() {
		ldd $1
	}
	withdebug() {
		LD_DEBUG=libs "$@"
	}
	SUFFIX=so
elif [[ "$(uname)" == "Darwin" ]]; then
	showinfo() {
		otool -L $1
		otool -l $1 | grep RC_RPATH
	}
	withdebug() {
		DYLD_PRINT_SEARCHING=1 "$@"
	}
	SUFFIX=dylib
fi

rm -rf dev

mkdir -p dev
mkdir -p dev/subdir
mkdir -p dev/bindir
mkdir -p dev/tmp

$CXX -o dev/libmylib.$SUFFIX -shared mylib.cpp
ln -s ../libmylib.$SUFFIX dev/subdir/libmylib-symlink.$SUFFIX

docheck() {
	showinfo $1
	withdebug $1
	(
		cd dev/tmp
		withdebug ../../$1
	)
}

echo "========= 1 ============="
$CXX -v -o dev/hello1 -L./dev hello.cpp -lmylib && docheck dev/hello1
echo "========= 2 ============="
$CXX -v -o dev/bindir/hello2 -L./dev hello.cpp -lmylib && docheck dev/bindir/hello2
echo "========= 3 ============="
$CXX -v -o dev/hello3 -L./dev/subdir hello.cpp -lmylib-symlink && docheck dev/hello3
echo "========= 4 ============="
$CXX -v -o dev/hello4 -L$PWD/dev hello.cpp -lmylib && docheck dev/hello4
echo "========= 5 ============="
$CXX -v -o dev/hello5 -L$PWD/dev -Wl,-rpath,./dev hello.cpp -lmylib && docheck dev/hello5
echo "========= 6 ============="
$CXX -v -o dev/hello6 -L$PWD/dev -Wl,-rpath,'$ORIGIN' hello.cpp -lmylib && docheck dev/hello6
echo "========= 7 ============="
$CXX -v -o dev/hello7 -L$PWD/dev -Wl,-rpath,'@loader_path' hello.cpp -lmylib && \
	install_name_tool -change dev/libmylib.dylib @rpath/libmylib.dylib dev/hello7 && \
	docheck dev/hello7
